export const EQUIPMENT_LABELS = {
  'barbell': '杠铃',
  'dumbbell': '哑铃',
  'body only': '自重',
  'cable': '绳索',
  'machine': '器械',
  'bands': '弹力带',
  'kettlebells': '壶铃',
  'foam roll': '泡沫轴',
  'medicine ball': '药球',
  'exercise ball': '健身球',
  'e-z curl bar': 'EZ杠',
  'other': '其他',
  'unknown': '未知',
  
  // New dataset equipment
  'assisted': '辅助自重',
  'band': '弹力带',
  'body weight': '自重',
  'bosu ball': '波速球',
  'elliptical machine': '椭圆机',
  'ez barbell': 'EZ弯杠',
  'hammer': '阻力锤',
  'kettlebell': '壶铃',
  'leverage machine': '杠杆器械',
  'olympic barbell': '奥林匹克杠',
  'resistance band': '阻力带',
  'roller': '滚轴',
  'rope': '战绳',
  'skierg machine': '滑雪机',
  'sled machine': '雪橇机',
  'smith machine': '史密斯机',
  'stability ball': '瑞士球',
  'stationary bike': '动感单车',
  'stepmill machine': '登山机',
  'tire': '轮胎',
  'trap bar': '环形杠',
  'upper body ergometer': '手摇单车',
  'weighted': '负重',
  'wheel roller': '健腹轮',
};
