export const MUSCLE_LABELS = {
  abdominals: '腹肌',
  abductors: '外展肌',
  adductors: '内收肌',
  biceps: '肱二头肌',
  calves: '小腿',
  cardiovascular: '心肺',
  chest: '胸肌',
  forearms: '前臂',
  glutes: '臀肌',
  hamstrings: '腘绳肌',
  lats: '背阔肌',
  lower_back: '下背',
  'lower back': '下背',
  middle_back: '中背',
  'middle back': '中背',
  neck: '颈部',
  quadriceps: '股四头肌',
  shoulders: '肩部',
  traps: '斜方肌',
  triceps: '肱三头肌',
  unknown: '未知',
};
