export const MUSCLE_LABELS = {
  abdominals: '腹肌',
  abs: '腹肌',
  abductors: '外展肌',
  adductors: '内收肌',
  biceps: '肱二头肌',
  calves: '小腿',
  cardio: '心肺有氧',
  cardiovascular: '心肺',
  'cardiovascular system': '心血管系统',
  chest: '胸肌',
  pectorals: '胸大肌/胸部',
  delts: '三角肌/肩部',
  forearms: '前臂',
  glutes: '臀肌',
  hamstrings: '腘绳肌',
  'hip flexors': '屈髋肌群',
  lats: '背阔肌',
  'levator scapulae': '肩胛提肌',
  lower_back: '下背',
  'lower back': '下背',
  middle_back: '中背',
  'middle back': '中背',
  'upper back': '上背',
  neck: '颈部',
  obliques: '腹斜肌',
  quadriceps: '股四头肌',
  quads: '股四头肌',
  'serratus anterior': '前锯肌',
  shoulders: '肩部',
  spine: '脊柱/竖脊肌',
  traps: '斜方肌',
  triceps: '肱三头肌',
  unknown: '未知',
  
  // Body part categories
  back: '背部',
  'lower arms': '前臂',
  'lower legs': '小腿',
  'upper arms': '上臂',
  'upper legs': '大腿',
  waist: '腰腹',
};

